// GENERATED by tools/make-sprites.sh -- do not edit by hand.
// Single-row sheets, so columns === frames. Stills are frames: 1.
// Keys are quoted: a source gif may be named anything, hyphens included.
export const SHEETS = {
    "bubu": { src: "sprites/bubu.png", w: 256, h: 240, frames: 8, fps: 11.1 },
    "bubu1": { src: "sprites/bubu1.png", w: 216, h: 240, frames: 4, fps: 11.1 },
    "bubu2": { src: "sprites/bubu2.png", w: 233, h: 240, frames: 13, fps: 10.0 },
    "bubu3": { src: "sprites/bubu3.png", w: 279, h: 240, frames: 12, fps: 11.1 },
    "bubu4": { src: "sprites/bubu4.png", w: 247, h: 240, frames: 12, fps: 30.8 },
    "bubu5": { src: "sprites/bubu5.png", w: 239, h: 240, frames: 9, fps: 4.8 },
    "bubu6": { src: "sprites/bubu6.png", w: 176, h: 240, frames: 12, fps: 10.0 },
    "bubu7": { src: "sprites/bubu7.png", w: 208, h: 240, frames: 16, fps: 12.5 },
    "goma-peach-bubu": { src: "sprites/goma-peach-bubu.png", w: 175, h: 240, frames: 25, fps: 20.0 },
    "dancing-animated": { src: "sprites/dancing-animated.png", w: 289, h: 340, frames: 10, fps: 20.0 },
    "dudu1": { src: "sprites/dudu1.png", w: 350, h: 340, frames: 18, fps: 10.5 },
    "dudu2": { src: "sprites/dudu2.png", w: 366, h: 340, frames: 7, fps: 8.3 },
    "fudu1": { src: "sprites/fudu1.png", w: 137, h: 140, frames: 1, fps: 1 },
    "fudu2": { src: "sprites/fudu2.png", w: 140, h: 140, frames: 1, fps: 1 },
    "fudu3": { src: "sprites/fudu3.png", w: 100, h: 140, frames: 1, fps: 1 },

} as const;

export type SheetName = keyof typeof SHEETS;
